# Generated by Django 6.0 on 2026-10-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_report_citizen_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='camera_model',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='report',
            name='has_exif_location',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='metadata_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='report',
            name='photo_source',
            field=models.CharField(blank=True, choices=[('camera', 'Şəkil çək (Kamera)'), ('gallery', 'Şəkil yüklə (Qalereya)')], default='gallery', max_length=20),
        ),
    ]
